[package]
name = "fit-reader"
version = "0.1.0"
authors = ["Erik Svensson <erik.public@gmail.com>"]
license = "MIT"
build = "build.rs"

[dependencies]
byteorder = "^1.1"
chrono = "0.4"

[build-dependencies]
xlsx-read = { git = "https://github.com/blueluna/xlsx-read.git" }
